import React from 'react'

const Head = () => {
  return (
    <>
        <title>Create Next App</title>
        <meta name="description" content="Generated By Momo" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    </>
  )
}

export default Head