import './globals.css'
import Link from 'next/link'
import {Montserrat} from "next/font/google"

const montserrat = Montserrat({
  weight: ['400','700'],
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-black text-white mx-20 py-12`}>
        {children}
        </body>
    </html>
  )
}
